name: Master
on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/5 * * * *'
jobs:
  build:
    environment: MAIN_KEY
    env:
      EMAIL_PASSWORD:${{secrets.EMAIL_PASSWORD}}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo Content
      uses: actions/checkout@v1
    - name: Setup Python ENV
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install Dependeinces
      run: pip install -r requirements.txt
    - name: Forfolio Watch Running
      run: |
        python stockscrap.py
